version: '3'

services:
  web:
    container_name: appFitter
    restart: always
    build: .
    ports:
      - '5000:4000'
    links:
      - 'mongo'
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    log_driver:
      driver: none
